name: Kulbot
description: "App kulbot"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "3.7.0"
  # sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get:
  permission_handler: ^11.3.1
  #flutter_chat_bubble: ^2.0.2
  flutter_bluetooth_serial: ^0.4.0

  flutter_joystick: ^0.2.1
  speech_to_text: ^7.0.0
  avatar_glow: ^3.0.1
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  wakelock_plus: 1.3.2
  #wakelock: ^0.6.2
  #highlight_text: ^1.7.0
  flutter_localization: ^0.2.0
  flutter_blue_plus: ^1.35.5

  #tflite_flutter: ^0.10.4
  camera: ^0.10.5+2
  #image: ^4.0.17
  path_provider: ^2.0.15
  #image_picker: ^1.0.0
  #exif: ^3.1.4
  # flutter_barcode_scanner: ^2.0.0
  # flutter_barcode_scanner: ^1.0.1
  mobile_scanner: ^3.5.2 #^7.0.0
  showcaseview: ^3.0.0
  # audioplayers: ^6.0.0
  shared_preferences: ^2.2.3 #^2.5.3
  fluttertoast: ^8.2.6
  #webview_flutter_plus: ^0.4.7
  sleek_circular_slider: ^2.0.1
  animated_toggle_switch: ^0.8.3
  #webview_flutter: ^4.8.0
  flutter_blockly_plus: ^1.4.1
  # flutter_blockly: ^1.5.1
  http: ^1.2.2
  flutter_slidable: ^3.1.1
  eva_icons_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/icon.png"
  min_sdk_android: 21

dependency_overrides:
  webview_flutter_android: ^3.14.0
  js: ^0.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/images/
    # - lib/assets/music/
    - assets/scratch/
    - assets/scratch/blocks/
    - assets/scratch/index.html
